# Generated by Django 6.0.2 on 2026-03-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='deptn0',
            new_name='deptno',
        ),
    ]
