# Generated by Django 6.0.2 on 2026-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_deptn0_dept_deptno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='hiredate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
